### ISSUE TITLE
[teamup-rocketchat] Provide meaningful log instead of panic details after crashing

### ISSUE THREAD

**Issue by roshanlc** [JankariTech/hubot#15]
Currently, the bot crashes showing message
```
TEAMUP-ROCKETCHAT-BOT 2023/01/11 09:05:30 Looking for configuration at "/var/www/rocket.chat/teamup/config.yml". Setting directory specified by configuration for log output.
TEAMUP-ROCKETCHAT-BOT 2023/01/11 09:05:30 open /tmp/teamup-rocket-chat.log: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x529229]

goroutine 1 [running]:
log.(*Logger).Output(0x0, 0x1?, {0xc000128200, 0x33})
	/usr/local/go/src/log/log.go:179 +0x89
log.(*Logger).Fatal(0xc0001281c0?, {0xc000125f00?, 0x441?, 0x7c41f0?})
	/usr/local/go/src/log/log.go:231 +0x45
main.main()
	/tmp/hubot/teamup-rocketchat-bot/main.go:307 +0x158
```
***
TODO: 
- Replace the above crash message with it's cause
E.g. `The bot has crashed due to following error: error_message`

**Comment by roshanlc** [comment]
Covered in PR #13

**Comment by roshanlc** [comment]
Covered in PR #13
